### ISSUE TITLE
Add 'is_a', 'part_of' attributes to edges

### ISSUE THREAD

**Issue by mikpom** [jdrudolph/goenrich#10]
Currently only 'is_a', 'part_of' are being read from ontology, but there is no way to distinguish one from another. At the same time this information can be easily incorporated into graph's edge data.
I believe storing this information is valuable.

**Comment by jdrudolph** [comment]
Thanks for opening this issue. At the moment I cannot make time to implement new features, so this will be low priority. You are welcome to make a pull request with the required changes.

**Comment by mikpom** [comment]
I was thinking that it is a good idea to implement Ontology class. At the core will the the same nx.DiGraph but many convenience methods can be added, for example to check if two terms constitute an ancestor - descendant pair, conveniently accessing terms by name etc.
What do you think?
Also it slightly goes out of initial GO enrichment purpose of the package.

**Comment by jdrudolph** [comment]
I really like the idea of having utility functions, which is exactly how `goenrich` is written. Currently there are no custom classes which makes the code super simple and makes all objects behave as expected (`pd.DataFrame`, `nx.DiGraph`). Improving e.g. the parsing and adding a few extra methods would be great. Maybe you could include a small code example exhibiting these new features in a somewhat useful way? This would make for great documentation for users.
