### ISSUE TITLE
Bonferroni correction actually makes results more significant

### ISSUE THREAD

**Issue by josiahseaman** [jdrudolph/goenrich#12]
When I used  `goenrich.enrich.analyze(O, query_genes, 'Background', method='bonferroni')` I was surprised to find that the q values were actually lower than the p values.  Is it possible the math in your bonferroni correction is backwards?

```
if method == 'bonferroni':
        q[mask] = p / len(p)
```
where it should probably be  `q[mask] = min(1, p * len(p))`

**Comment by jdrudolph** [comment]
Well spotted! You are definitely correct. I'll try to find some time to apply the fix, or you can go ahead and make a pull request. Thank you for reporting this.

**Comment by jdrudolph** [comment]
Fixed by 68ee3f7. A fixed version `1.10.2` was already released and `goenrich` can be updated with `pip`.
Thanks again @josiahseaman
