### ISSUE TITLE
Possibly unaccounted file version dependency in unittests?

### ISSUE THREAD

**Issue by srcoulombe** [jdrudolph/goenrich#18]
I'm revising my pull request (https://github.com/jdrudolph/goenrich/pull/15) to fix https://github.com/jdrudolph/goenrich/issues/14, and while running unittests I kept coming across the following error:

```
FAILED goenrich/tests/test_enrichment.py::TestGoenrich::test_analysis_and_export - AssertionError: 18 != 8
```
I really can't think of any reason why this unittest wouldn't pass other than a difference in the ```go-basic.obo``` or ```gene2go.gz``` files I've downloaded. Would it be possible to share the files that were used for testing purposes to check that possibility?

**Comment by jdrudolph** [comment]
I made the unit test less strict. Hopefully now it will be less brittle.
