### ISSUE TITLE
Howdy from the scikit-bio team

### ISSUE THREAD

**Issue by ebolyen** [jdrudolph/goenrich#3]
@jdrudolph sorry we didn't see your Gitter message earlier, none of us received an email update.

We've discussed your package internally and we think it would be a really cool addition to scikit-bio.
If you are still willing to integrate the package, we would be happy to guide you through the process. 

Let us know if you are still interested!

ping: @jairideout @gregcaporaso

**Comment by jdrudolph** [comment]
The development of `goenrich` will continue independently of the `scikit-bio` project
