### ISSUE TITLE
update for new pandas version to avoid AttributeError. 

### ISSUE THREAD

**Issue by keoughkath** [jdrudolph/goenrich#5]
This is a great package, I'm really enjoying it! I am, however, getting an error that should be solved by updating this package to support the newest version of Pandas which has retired .sort in favor of .sort_values. 

**Command:** 

options = { 'min_category_size' : 2, 'max_category_size' : 100000,
    'max_category_depth' : 100000 }
enrichment = goenrich.enrich.analyze(O, query, 'reference', **options,gvfile='bin36.dot').dropna().sort_values(by='q')

**Error:** 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-93-fe685c6ffc5b> in <module>()
      3 options = { 'min_category_size' : 2, 'max_category_size' : 100000,
      4     'max_category_depth' : 100000 }
----> 5 enrichment = goenrich.enrich.analyze(O, query, 'reference', **options,gvfile='bin36.dot').dropna().sort_values(by='q')
      6 enrichment.head()

/pollard/home/kathleen/tools/anaconda3/lib/python3.5/site-packages/goenrich/enrich.py in analyze(O, query, background_attribute, **kwargs)
     36         if show.startswith('top'):
     37             top = int(show.replace('top', ''))
---> 38             sig = df.sort('q').head(top)['term']
     39         else:
     40             raise NotImplementedError(show)

/pollard/home/kathleen/tools/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py in __getattr__(self, name)
   2968             if name in self._info_axis:
   2969                 return self[name]
-> 2970             return object.__getattribute__(self, name)
   2971 
   2972     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'sort'

Thanks!
Kathleen

**Comment by jdrudolph** [comment]
glad you like it! thanks for reporting this issue.
