### ISSUE TITLE
Propagate direction

### ISSUE THREAD

**Issue by mikpom** [jdrudolph/goenrich#7]
Hi!
I was exploring the output of goenrich and was concerned that sometimes it returned to many significantly enriched terms.
After exploring the source code I realized that propagate method goes down the ontology tree though I think it should be reversed. 
For example there are genes annotated with GO:0002360 (T cell lineage commitment). And currently propagate will add those genes to it's child term GO:0002365 (gamma-delta T cell lineage commitment). But this should not be true since gene involved in T cell lineage commitment not necessarily has to be involved in gamma-delta commitment. Vice versa is true though.
So shouldn't propagate method start as 
`for n in reversed(list(nx.topological_sort(O))):`

instead of
`for n in nx.topological_sort(O):`      
????

-Mikhail

**Comment by jdrudolph** [comment]
you are correct in how the propagation should work and I believe this is exactly how it's done. The ontology tree `O` is already 'reversed', meaning that edges go from more specific to less specific, i.e. up the tree.

**Comment by mikpom** [comment]
So for example I run commands from the tutorial. After that I get
```
In [18]: len(O.node['GO:0002360']['gene2go'])
Out[18]: 1696

In [19]: len(O.node['GO:0002365']['gene2go'])
Out[19]: 1700
```
But fewer genes should be annotated with GO:0002365 because it is more specific.

**Comment by jdrudolph** [comment]
I'm having trouble to recreate the numbers you obtained. I ran the following script:
```python
import goenrich
O = goenrich.obo.ontology('db/go-basic.obo')
gene2go = goenrich.read.gene2go('db/gene2go.gz')
values = {k: set(v) for k,v in gene2go.groupby('GO_ID')['GeneID']}
background_attribute = 'gene2go'
goenrich.enrich.propagate(O, values, background_attribute)
t_cell_lineage_commitment = 'GO:0002360'
print('More general:', len(O.node[t_cell_lineage_commitment][background_attribute]))
gamma_delta_t_cell_lineage_commitment = 'GO:0002365'
print('More specific:', len(O.node[gamma_delta_t_cell_lineage_commitment][background_attribute]))
```
I obtained 18 annotations for the more general and 0 annotations for the more specific term...

**Comment by mikpom** [comment]
Figured that out!!!
It is a quirk with networkx 2.0
With V 2.0 I ran the script you provided and still got the results 1696/1700. 
When I enforced neworkx 1.9 I got the results as yours.

**Comment by jdrudolph** [comment]
Happy to hear and very interesting!
Would you mind commenting on the how/why the behavior changes for networkx 2.0

**Comment by mikpom** [comment]
I will try to figure out why the problem occurs.
Networkx actually have guidlines how to write code working with both versions.  This will take some time though.

**Comment by mikpom** [comment]
I mean the code should be migrated to nx 2.0 or made working with both version. Otherwise I do not think the issue is closed.

**Comment by jdrudolph** [comment]
let's just open a separate issue/pull-request for networkx 2.0 support.
